kitbagjs/router

- src/types/invalidRouteParamValueError.ts
- src/types/params.ts
- src/types/routeMethods.test-d.ts
- src/types/routeMethods.ts
- src/utilities/params.test.ts
- src/utilities/params.ts
- src/utilities/path.ts
Introduces two new utilities `getParamValue` and `setParamValue`. These are intended to be used to transform a typed param to and from a string. 
`getParamValue` accepts a string value and a `Param` and then determines how to parse the string value based on the param given.
`setParamValue` accepts a typed value and a `Param` and then determines how to stringify the value based on the param given.
A `Param` can be `ParamGetter | ParamGetSet | RegExp | BooleanConstructor | NumberConstructor`.
> Update param type and write get/set utilities

- src/types/routeMethods.test-d.ts
- src/types/routes.ts
- src/types/utilities.ts
- src/utilities/createRouter.spec.ts
- src/utilities/createRouter.ts
- src/utilities/flattenRoutes.spec.ts
Makes component a required property of a `ChildRoute` and an optional property on `ParentRoute`. Updates tests to add components where necessary.
> Add `component` property and types to `Route` types

- src/utilities/flattenRoutes.spec.ts
- src/utilities/flattenRoutes.ts
adjusted logic for flatten routes regex, param names must be letters only and now support optional params
> updated param logic on flatten routes utility

- src/types/routeMethods.test-d.ts
- src/types/routeMethods.ts
- src/types/utilities.ts
Loosely conforms the types for route params to match params that end with a `/ `, `-`, or `_`. 
This is accomplished by replacing `-` and `_` with `/` on each path prior to parsing out the params. Then `/` is used same as before. Each character we want to support requires a `ReplaceAll<path, '-', '/'>` type to wrap the path. This is recursive template literal type. So I think there probably is some cost to doing this. 
For that reason there are some other special characters that I'm not accounting for here that are valid url characters are `.`, `!`, `~`, `*`, `'`, `(`,  and `)`. Which are not commonly used. I vote we only add this if necessary but I don't feel strongly.
> Match alphanumeric params only

- src/types/routeMethods.ts
- src/utilities/path.ts
Path originally just returned the same types as its arguments. Which was never really correct but allowed for all the other types to be written. Implementing the type path should actually return by having all route method types use Path and having Path be responsible for extracting param types.
> Path types

- src/types/routeMethods.ts
Fixes single param not being a tuple
> Make sure to always return a tuple for params in ExtractParamsFromPathString

- src/types/routeMethods.ts
- src/utilities/createRouter.ts
Fills out the `Router` type. Decided to leave the `routeMatch` method as part of the router for now to avoid making this change bigger.
> Router types

- src/types/params.ts
- src/utilities/paramValidation.ts
- src/utilities/params.spec.ts
- src/utilities/params.ts
- src/utilities/paramsFinder.spec.ts
- src/utilities/paramsFinder.ts
works similar to what was named `findParamValues` but in reverse.
takes `path: string`, and an optional ParamReplace (solution to what would be 4 params and making all optional)
```ts
{
name: string,
params: Param[],
values: unknown[],
}
```
finds that param in path and replaces with param setter value
I'm tempted to rename `paramsFinder` now that it has both `getParamValues` and `setParamValues`, any suggestions?
> created setParamValue function in paramsFinder service

- src/utilities/createRouter.ts
- src/utilities/urlAssembly.spec.ts
- src/utilities/urlAssembly.ts
utilizes `setParamValuesOnUrl` to take `Resolved<Route>` and `Param` arguments to assembly complete URL string. Will eventually be part of the implementation of RouteMethods
> implemented url assembly utility

- src/types/routeMethods.test-d.ts
- src/types/routeMethods.ts
- src/types/utilities.ts
Fixes the types for `RouteMethodResponse` so that both the sync and async values are the same. 
An example of implementing this type is [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBASg9gV2BAshYALOATGEDOYcAdvtALxQDeAUFPVAgE4A2AXFPsEwJbEDmdBpgjEOABSZwAtjzIAZHgGsIAHgDys4KvhJU6LLgJFSEADRQA5COKWAfHYDa1jKMsBdGgF8aNAGYIxADGwDwkUFJ6ABQAlBy6yGiYOHiEJGTUQvRB6cARxukQHJo82gn6yUZpphYubnZQlLQMLYysHJZ+cHCWWVA+fTmkeTYAhgBGLEWwiIkGKQWmjZmtDMzsVl09Zn0tNhxQUUwEMY0NxBAA7lCSMnJqJWWzFYapJmS1NvZ2UUcEcCwAG4QU7kBpkYAAFR40ggs1+oIax3wAOBf2qZBiFgAjAAGfExGIAOhs6KxfQGLWOwGYxCgY0mEG8viGXGobRY-WWkWQsRorIBECJLDg-CilnwIGClgs6xivgA3FFRpLgodESsGKy8lQOV5lqNLqNShFnrEFYN0oLhaLxSqpUEZRz5V4YuagA)
> Fix types for RouteMethodResponse

- src/types/routeMethods.test-d.ts
- src/types/routeMethods.ts
- src/types/utilities.ts
Previously if a leaf was not public it would still show up in the `RouteMethods` type but with the type of `never`. This tweaks the `Identity` utility type to remove properties if their type is `never` and wraps the `RouteMethods` type definition in `Identity` to remove these properties.
> Fix route methods showing up in types with `never`

- src/utilities/createRouter.ts
- src/utilities/routerNavigation.browser.spec.ts
- src/utilities/routerNavigation.spec.ts
- src/utilities/routerNavigation.ts
- src/utilities/updateBrowserUrl.spec.ts
- src/utilities/updateBrowserUrl.ts
Makes `updateBrowserUrl` a promise. Never resolves when the update is not same origin. 
Updates `createRouterNavigation` to better support both node and browser environments
Updates `createRouter` to implement navigation and simplify implementation of router navigation methods.
> Update navigation and implement onLocationUpdate logic

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/components/RouterView.vue
- src/components/index.ts
- src/main.ts
- src/utilities/createRouter.ts
- tsconfig.json
- vite.config.js
this PR adds router-view, but only as stub, the real value of this PR is all the supporting infrastructure needed to export vue components with the library
this PR also removed the script and github workflow to run `tsc --no-emit` per the recommendation by vitest at the bottom of [this page](https://vitest.dev/guide/testing-types#testing-types)
> add support for vue components as part of library export

- package-lock.json
- package.json
- src/components/RouterView.vue
- src/components/helloWorld.ts
- src/components/index.ts
- src/components/routerView.browser.spec.ts
- src/components/routerView.ts
- src/types/routes.ts
- src/types/utilities.ts
- src/utilities/createRouter.ts
- src/utilities/resolveRoutes.ts
- src/utilities/routeMatch.ts
Adds a basic implementation for the `RouterView` component. Changed the existing boilerplate component from a sfc to a basic typescript component with a render function. 
- Removed `vue-tsc` as a dependency (everything seems to work fine without it)
- Added `@vue/test-utils`
Notes:
I don't like how in `RouterView` the types for the route component need some coercion. Seems like its getting an expanded type for some reason and typescript cannot sort it out.
> Implement RouterView

- src/compositions/useRoute.ts
- src/compositions/useRouteParam.ts
- src/compositions/useRouteParamRaw.ts
- src/types/middleware.ts
- src/types/routeMethod.ts
- src/types/routeMethods.spec-d.ts
- src/types/routeMethods.ts
- src/types/router.ts
- src/types/utilities.ts
- src/utilities/createRouteMethods.spec.ts
- src/utilities/createRouteMethods.ts
- src/utilities/createRouter.ts
- src/utilities/urlAssembly.ts
- Moved `Router` and associated types into `@/types/router`
- Moved `RouteMethod` and associated types into `@/types/routeMethod`
- Updated `RouteMethod` type to match what we discussed at standup
- Updated `createRouteMethods` to implement the route methods to match the expected type
- Wrote unit tests
> Implement route methods and organize router and route method types

- src/types/flattened.spec-d.ts
- src/types/flattened.ts
- src/types/index.ts
- src/types/routeMethods.ts
Introduces a new type called `Flattened` that accepts `Route | Routes`. Produces a flag record keyed by the dot notation name of the route with values of each individual route's params
WIP - Need to add tests
> Add type for flattening routes into an object of route & params pairs

- src/types/params.ts
- src/types/routeMethods.ts
- src/types/routes.ts
- src/utilities/params.ts
- src/utilities/path.ts
- src/utilities/query.ts
Adds initial type support for query params on `Route`. This works very similarly to out path params work. `Route.query` is type `string | Query`. 
This example has three params. `name`, `gender`, and `age`. `name` and `gender` are required, `age` is optional. All are strings.
```typescript
const route = {
name: 'route',
path: '/route',
query: 'name=:name&gender=:gender&age=:?age'
} as const satisfies Route
```
Same example but using the `query` utility to make the `age` param a `number`
```typescript
const route = {
name: 'route',
path: '/route',
query: query('name=:name&gender=:gender&age=:?age', {
age: Number
})
} as const satisfies Route
```
This is not implemented. Didn't want to get to far without discussing. But the idea is that any route that has a query would require those params …
> RFC: Add type support for route query

- src/types/flattened.spec-d.ts
- src/types/flattened.ts
- src/types/routeMethods.spec-d.ts
- src/types/routeMethods.ts
Updates both the `Flattened` and the `RouteMethods` types (and their individual pieces) to support query params.
> Update route method and flattened types to support query params

- src/types/flattened.ts
- src/types/routeMethods.ts
- src/types/router.ts
- src/types/routes.ts
- src/types/utilities.ts
- src/utilities/createRouteMethods.spec.ts
- src/utilities/createRouteMethods.ts
- src/utilities/createRouter.spec.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterPush.ts
- src/utilities/routerNavigation.ts
Updates the types for `RouterPush` to be a little more accurate. Was hoping to remove the need for an `as any` but still had that same issue in `createRouterPush`. But at least now its consistent with `createRouteMethods`.
> More complete types for `RouterPush` and abstact implementation into `createRouterPush`

- src/types/router.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterPush.spec.ts
- src/utilities/createRouterPush.ts
- src/utilities/createRouterResolve.browser.spec.ts
- src/utilities/createRouterResolve.ts
Moves the logic for determining the url from a route source out of createRouterPush and into createRouterResolve. Also adds `resolve` to the `Router` type so it can be used in other applications like in `RouterLink`
> Abstract resolving a url from a route source into router.resolve

- src/types/routes.ts
We're using consts and inference so we don't actually need these generics.
> Remove generics from route types

- .github/workflows/test.yml
- package.json
- tsconfig.json
- vite.config.js
Better devx so test:types can run without picking up source errors.
> Separate out type checking from the type tests

- src/types/routeMethod.ts
- src/types/routeMethods.ts
- src/types/router.ts
- src/utilities/createRouteMethods.spec.ts
- src/utilities/createRouteMethods.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterPush.spec.ts
- src/utilities/createRouterPush.ts
Adding more general implementation types for internal utilities so that we don't have to pass so many generics around. I think this will make development and testing simpler. 
I'm not attached to this idea. But it felt kinda nice when making these changes. 
The idea is that internal utilities like `createRouteMethods`, and `createRouterPush` return wider `Implementation` types that don't use generics. I think this means there will be less typescript depth but not totally sure. Either way several methods got simpler.
> RFC: Implementation types for internal utilities

- src/types/middleware.ts
- src/types/resolved.ts
- src/types/routeMatchRule.ts
- src/types/router.ts
- src/utilities/createResolvedRoute.ts
- src/utilities/createRouteMethods.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterReject.ts
- src/utilities/createRouterResolve.ts
- src/utilities/createRouterRoute.ts
- src/utilities/middleware.ts
- src/utilities/resolveRoutes.spec.ts
- src/utilities/resolveRoutes.ts
- src/utilities/routeMatch.browser.spec.ts
- src/utilities/routeMatch.ts
- src/utilities/routeMatchScore.ts
- src/utilities/routeRegex.ts
- src/utilities/routes.ts
- src/utilities/urlAssembly.ts
Cleans up `Resolved` type to be simpler based on decision to make it an internal only type. Will follow this with a PR to remove Resolved from things like router.route and middleware types
- Removes generic `Route` since there's no reason to type guard this type
- Removes symbol properties in favor of strings
- Renames to `ResolvedRoute`
> Simplify `Resolved<T>` type to `ResolvedRoute`

- src/components/routerLink.browser.spec.ts
- src/components/routerLink.vue
- src/types/router.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterFind.ts
added `router.find` method
takes `source`, same type as `router.push` and `RouterLink.to`
first calls `resolve` to convert source into url, then passes that url into existing `routeMatch` logic
returns `ResolvedRoute | undefined`
> Router link classes

- src/utilities/createRouter.ts
- src/utilities/createRouterPush.spec.ts
- src/utilities/routerNavigation.browser.spec.ts
- src/utilities/routerNavigation.spec.ts
- src/utilities/routerNavigation.ts
now when you create `Navigation` you pass `onBeforeLocationUpdate` and `onAfterLocationUpdate`
which should enable us to have our hooks actually run before browser knows about the route, making them abortable
> add support for BEFORE navigation update

- src/utilities/paramValidation.spec.ts
- src/utilities/paramsFinder.spec.ts
- src/utilities/paramsFinder.ts
- src/utilities/routeRegex.spec.ts
- src/utilities/routeRegex.ts
While setting out to prove param name is case sensitive I found and fixed a bug with regex utilities when multiple params
We have 2 major places we use regex utilities
1. routeRegex.ts -> responsible for taking a `path` and giving back the pattern we use to check if a given url "matches" the expectation of this routes path (used for route matching)
2. paramsFinder.ts -> responsible for getting and setting param values to/from a url (use for url building)
The bug was in param finding, when looking for a param value it would take a path like
```
/somewhere/:id
```
and when you ask for it to find "id", you get back
```
/somewhere/(fancy-capture-group)
```
Things seemed fine with all the tests we had thrown at it until I wrote a test for multiple params with different cases. In that test I …
> Discovered bug while proving Param names are case senstitive

- src/errors/navigationAbortError.ts
- src/errors/navigationDoneError.ts
- src/utilities/createRouter.ts
- src/utilities/routerNavigation.ts
Updates navigation to provide context methods for the `onBeforeLocationUpdate` hook to allow for control over what happens next. Currently providing `done` and `abort` methods. `done` instructions navigation to finish updating the location but then to stop prior to running `onAfterLocationUpdate`. `abort` prevents the location from being updated at all. 
I haven't yet added support for `abort` in hooks with a timing of `before`. That will be in a future PR.
> Add support for running route hooks in before location update hook

- src/compositions/hooks.ts
- src/models/RouteHookStore.ts
- src/models/RouteHooks.ts
- src/types/hooks.ts
- src/types/router.ts
- src/types/routes.ts
- src/utilities/createRouter.ts
- src/utilities/createRouterHooks.ts
- src/utilities/createRouterReject.ts
- src/utilities/getRouteHooks.spec.ts
- src/utilities/getRouteHooks.ts
- src/utilities/hooks.spec.ts
- src/utilities/hooks.ts
Prior to this there was a single utility for executing route hooks that would return a boolean based on if something like a `push`, `replace`, or `reject` happened. This wasn't enough information for the `update` method in `createRouter` to know what to do. 
I've added stronger types for `BeforeRouteHook` and `AfterRouteHook` and defined types for `BeforeRouteHookResponse` and `AfterRouteHookResponse`. Each response has a status like `abort`, `push`, `reject`, or `success`. The `abort` status is new altogether and is only included for before hooks.
> Refactor of how hooks are run to account for different timing and outcomes

- README.md
- docs/getting-started.md
follows pattern established by @kitbag/mapper and @kitbag/events
- really only covers what's in "getting-started" of vitepress site
- links to vitepress site at the top
- note both `npm` and `zip` badges will not work until we have any version of @kitbag/router published on npm
> setup basic readme

- package.json
- src/components/routerView.vue
- src/types/router.ts
- src/utilities/createRouter.ts
- src/utilities/createRoutes.spec.ts
- src/utilities/createRoutes.ts
- vite.config.js
previously, if a child route rendered RouterView it would cause infinite loop. This PR moves responsibility for defaulting component to `createRoutes` method. 
side quests
- fixes vue external dep on vite build
- fixed bug with incorrect sort for matches, should be greatest ancestor -> least descendent
- attempts to fix type error when using plugin (could have been related to npm link)
- bumps version back to what's published on npm
- moves vue to peerDep
> RouterView as default route component

- src/utilities/createRoutes.ts
`isParentRoute` accurately guards that `children` will exist.
> Remove children check in createRoutes

- src/components/routerLink.browser.spec.ts
Tiny cleanup. We don't need these anymore now that our types are not recursive.
> Remove spyOn generics

- docs/.vitepress/config.ts
- docs/advanced-concepts/route-matching.md
- docs/core-concepts/navigating.md
- docs/core-concepts/route-params.md
- src/utilities/params.ts
- src/utilities/paramsFinder.ts
- src/utilities/routeMatchRegexRules.spec.ts
- src/utilities/routeMatchScore.spec.ts
- src/utilities/routeMatchScore.ts
- src/utilities/routeRegex.ts
while documenting route matching I discovered a bug with query regex matching when the value is static
```ts
const route = {
...
query: 'foo=bar'
}
```
the regex was not asserting end of the value as either `&` or `$` (ampersand or end of input). This meant the following would be considered a match
- ?foo=bar
- ?foo=barrrr
- ?foo=barameter&zoo=keeper
Also while documenting route scoring I thought it was strange that we rank routes higher for having provided query params that are optional but not doing the same for path params. This  means
```ts
const route = {
...
path: /:?optionalA/:?optionalB/:?optionalC
query: 'foo=:?optionalFoo'
}
``` 
would choose 
- "///?foo=bar"
over
- "/fulfilledA/fulfilledB/fulfilledC"
even though the ladder fulfills 3 optional params and the former only 1
both …
> Route matching updates

- docs/advanced-concepts/route-matching.md
- src/utilities/paramsFinder.ts
- src/utilities/routeMatchScore.ts
- src/utilities/routeRegex.spec.ts
- src/utilities/routeRegex.ts
- src/utilities/urlAssembly.ts
- src/utilities/withQuery.ts
fixes (2) bugs discovered in testing a recent PR
- because setting param values on query was trying to set params across both path and query it wasn't escaping the "?" in regex which caused some weird downstream effects. Now I set values like I get the values, separately on path and query THEN combine
- optional query params still expected the "key" to be present. So `/route?with=:?param` would match `/route?with=`, `/route?with`, but not  `/route`. My solution to this was to update the RouteMatchRule for query matches to only check required params. Any mis-types for optional params would get caught in the RouteMatchRule for params.
> fixed a couple bugs with query regex

- docs/advanced-concepts/route-matching.md
- docs/advanced-concepts/route-meta.md
- src/types/route.ts
- src/types/routeProps.ts
- src/utilities/createRouterReject.ts
- src/utilities/createRoutes.spec.ts
- src/utilities/createRoutes.ts
- src/utilities/getRouteHooks.spec.ts
- src/utilities/hooks.spec.ts
- normalize `matched.meta` to always be empty object so devs don't have to check for undefined
```ts
// without
route.metached.meta?.thing
// with
route.matched.meta.thing
```
- update types for RouteMeta to be `Record<string, unknown>` so regardless of if devs override interface all string keys will be accepted and value defaults to unknown
- docs updated
> Route meta documented

- src/services/createRoutes.ts
- src/services/paramValidation.ts
- src/services/routeMatchScore.ts
- src/services/urlAssembly.ts
- src/types/resolved.ts
- src/types/route.ts
- src/types/routesMap.ts
drop separate params buckets in favor of combined path and query which also contain params
> fix children not having param context of parent

- src/errors/routeDisabledError.ts
- src/errors/routeNotFoundError.ts
- src/services/createRouterFind.spec.ts
- src/services/createRouterResolve.spec.ts
- src/services/createRouterResolve.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/routeMatchRules.spec.ts
- src/services/routeMatchRules.ts
- src/types/routeWithParams.spec-d.ts
- src/utilities/testHelpers.ts
Adds a route match rule for host to make sure that `http://example.com` doesn't match a route with path `/`. This would previously match because the path for `https://example.com` is `/`. So we need to check the host itself. 
Closes https://github.com/kitbagjs/router/issues/179
> Fix router.find returning any route with `/` as the path when resolving an external url with no path

- src/services/createRouterResolve.spec.ts
- src/services/getParamsForString.ts
- src/services/routeRegex.ts
Since the param regex only looked for `\w` characters any param name that was snake or kebab case would not work. Adding `-` and `_` to the regex patterns fixes this.
Closes https://github.com/kitbagjs/router/issues/144
> Fix param names unable to be snake or kebab case

- src/components/routerView.browser.spec.ts
- src/components/routerView.vue
- src/services/createRoutes.spec.ts
- src/services/createRoutes.ts
- src/types/routeProps.ts
Adds the ability for a route to define multiple components rather than a single component. These components can then be rendered using named router views. A router view with no name will render the `default` component which is either `route.component` or `route.components.default`.
Closes https://github.com/kitbagjs/router/issues/174
Needs docs
**main.ts**
```ts
const routes = createRoutes([
{
name: 'parent',
path: '/',
components: {
default: { template: '<p>default</p>' },
one: { template: '<p>one</p>' },
two: { template: '<p>two</p>' },
},
},
])
...
```
**App.vue**
```vue
<template>
<RouterView name="one" />
<RouterView />
<RouterView name="two" />
</template>
```
**Rendered html** 
```html
<p>one</p>
<p>default</p>
<p>two</p>
```
> Named router views

- src/services/params.ts
- src/types/params.ts
- src/types/path.ts
- src/types/query.ts
- src/types/resolved.ts
- src/types/route.spec-d.ts
- src/types/route.ts
- src/types/routeWithParams.ts
- Improved the way we capture optional params in type system. 
- previously we were defining the param inside of `params` as `StringConstructor | undefined` for example. So basically if a Param has `| undefined`, it meant it should be optional. 
- this adds the complication of having to check for missing values and is redundant since we can derive the fact that it's optional by looking for the optional symbol in the Param.
- I updated the definition for `ResolvedRoute` so that if it's created without a generic (using the default), it will widen params to `Record<string, unknown>`, otherwise it would be `{}`.
- path and query types have stronger typed defaults, when used without defaults will have `Record<string, Param>` for `params`.
> Improved path query types

- docs/.vitepress/config.ts
- docs/api/functions/path.md
- docs/api/functions/query.md
- docs/core-concepts/defining-routes.md
- docs/core-concepts/query-params.md
- docs/core-concepts/route-params.md
this PR updates documentation for [default value in params](https://github.com/kitbagjs/router/pull/195).
this PR merges path-params and query-params into route-params which removed much of the duplication of explaining params for both. There is still a page for query-params, which covers only the important differences.
> Param default docs

- src/services/component.browser.spec.ts
- src/services/component.ts
https://github.com/kitbagjs/router/pull/164 introduced the `component` utility which allowed binding props and attrs directly to route components. But it always required suspense because even if the props getter was not async it would wrap it in an async component. 
This PR fixes that by only wrapping the component in an async component IF the getter returns a promise.
> Update component utility to not require suspense unless props are async

- src/components/routerView.vue
- src/compositions/useLink.ts
- src/services/combineName.spec.ts
- src/services/createCurrentRoute.ts
- src/services/createRouter.spec.ts
- src/services/createRouterFind.ts
- src/services/createRouterReject.ts
- src/services/createRouterResolve.ts
- src/services/createRouterRoute.spec.ts
- src/services/createRouterRoute.ts
- src/services/createRoutes.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/getRouteHooks.spec.ts
- src/types/resolved.ts
- src/types/route.ts
- src/types/routeProps.ts
- src/types/routerPush.ts
- src/types/routerReplace.ts
- src/types/utilities.ts
- src/utilities/testHelpers.ts
The `isRoute` type guard was functionally sound and types work just fine. But `RouterRoute` produced a type that was too specific and to wide. So when passing a `RouterRoute` into `isRoute` the types conflicted and effectively didn't narrow properly. A few changes were necessary to fix this.
1. Update `Route` type to default to a `string` for the key rather than `any`. Because `any & 'key'` is still `any`. But `string & 'key'` is `'key'`. Which is what we want. 
2. Remove `Omit` utility from `RouterRoute` declaration. This produces a much simpler type and one that typescript can reason about without evaluating it.
3. Replace all `DeepReadonly` types with `Readonly` to produce simpler types that typescript can reason about more easily (and produce much more readable types)
4. Remove all …
> Fix `RouterRoute` type so that `isRoute` type guard works correctly when given a `RouterRoute`

- src/services/createRouterReject.ts
Hopefully temporary fix to get the build working again. Related to 
https://github.com/qmhc/vite-plugin-dts/issues/283 and https://github.com/microsoft/rushstack/issues/3875
Might look at removing `vite-plugin-dts` in favor of using `vue-tsc` to extract types.
> Remove `as const` to fix build

- src/components/routerView.browser.spec.ts
- src/compositions/useRoute.ts
- src/guards/routes.spec-d.ts
- src/guards/routes.ts
- src/services/createCurrentRoute.ts
- src/services/createRouter.spec.ts
- src/services/createRouter.ts
- src/types/params.ts
- src/types/register.ts
- src/types/resolved.ts
- src/types/routeUpdate.ts
- src/types/router.ts
This PR updates the type for the current route to be a discriminating union of possible routes. This means that when accessing the route via `router.route` or by using the `useRoute` composition the route can easily be narrowed. 
Given the following routes
```ts
const routes = createRoutes([
{
name: 'parentA',
path: '/parentA',
children: createRoutes([
{
component,
name: 'childA',
path: '/childA/[paramA]',
},
]),
},
{
name: 'parentB',
path: '/parentB',
component,
},
])
const router = createRouter(routes)
```
`router.route.key` is type `'parentA' | 'parentB' | 'parentA.childA'`. And `router.route.params` is type `{} | { paramA: string }`. Which means you can narrow the route in a type safe way by doing things like this
```ts
const route = router.route
if(route.key === 'parentA.childA') { …
```
> Make `route` a union of all possible routes and improve return types for `isRoute` and `useRoute`

- src/types/route.ts
`Route` had some normalization and logic built into it that we no longer need because we're normalizing the data itself when we create the route. So we can remove the extraneous coercion and loose generic types.
> Simplify the`Route` type

- docs/.vitepress/config.ts
- docs/advanced-concepts/route-narrowing.md
- docs/api/composables/useRoute.md
- docs/api/guards/isRoute.md
- docs/core-concepts/composables.md
- docs/core-concepts/defining-routes.md
Little cleanup of docs in general. 
- Added the missing "Composables" page to core concepts (previously only accessible via search and was listed as an advanced concept). 
- Added "Route Narrowing" to advanced concepts
- Updated api docs for `isRoute` and `useRoute`
- Removed some references to "route methods" that were outdated
> Update docs to include a guide about narrowing the route

- src/components/routerLink.vue
Solution was to update click handler on underlying `a` tag, avoid pushing to router if route is external.
This solution is incomplete. A better solution will be moving this responsibility deeper into router. That would also prevent this bug if a developer calls `router.push('https://router.kitbag.dev')`. Currently the router-link compares the host of the resolved url against `window.location.host`. We probably shouldn't move that similar logic into the router since we can't guarantee the user isn't in a Node environment. 
I will continue working towards a more complete solution. I'm considering, and welcome feedback on the following ideas:  
- adding `host` as an option when calling `createRouter` 
- pulling host off the `initialUrl`
- checking what history mode, possibly using `window` …
> bug: external `to` on router-link was rendering NotFound before navigating

- src/services/combinePath.ts
- src/services/combineQuery.ts
- src/services/createRoutes.ts
- src/services/getParamsForString.ts
- src/services/path.spec.ts
- src/services/query.spec.ts
- src/utilities/checkDuplicateKeys.ts
Before this PR, the logic for checking duplicate keys always relied on `checkDuplicateKeys` utility except in src/services/getParamsForString.ts, where it would just look for the param value to be inside the object we're building for "paramsForString". 
The issue with this is the "paramName" is assumed to be without leading "?", but the keys of the "paramsForString" might include a leading "?" so it will appear to not be a duplicate.
The solution to this issue is to use `checkDuplicateKeys` like we do everywhere else, but offer an overload to make it easier to use here.
(optionally) I decided to also move the responsibility of throwing `DuplicateParamsError` inside the utility. This means not having to import and use the error in all the places we check, but also removes a weird return …
> fix bug where duplicate keys aren't caught

- src/guards/routes.spec-d.ts
- src/services/combinePath.ts
- src/services/combineQuery.ts
- src/types/index.ts
- src/types/params.ts
Seems that all params are coming in as `string`, updated test to test param types other than just string.
This issue was previously discovered at runtime when calling `path` (or `query`) and passing in an existing `path` (or `query`). The issue is that the user facing type for params argument is without leading "?", but the internal return type will use leading "?" to denote optional params. 
So a route defined as 
```ts
path('[?foo]', ...)
```
will expect a 2nd argument with key `foo` (no question mark) 
```ts
path('[?foo]', { foo: Number })
```
even though the return type for params will be
```ts
{ '?foo': Number }
```
When passing those params in for a subsequent creation of `path` will look for `foo` in params and not find it because of the leading question mark present. This was …
> bug with `isRoute` param types

- src/services/createExternalRoutes.spec.ts
- src/services/createExternalRoutes.ts
- src/services/createRouterResolve.spec.ts
- src/services/createRoutes.ts
- src/services/host.spec.ts
- src/services/host.ts
- src/services/paramValidation.spec.ts
- src/services/urlAssembly.spec.ts
- src/services/urlAssembly.ts
- src/types/externalRouteProps.ts
- src/types/flattenRoutes.ts
- src/types/host.ts
- src/types/register.ts
- src/types/resolved.spec-d.ts
- src/types/route.spec-d.ts
- src/types/route.ts
- src/types/routeWithParams.spec-d.ts
- src/types/routeWithParams.ts
- src/types/routesMap.spec-ts.ts
- src/utilities/checkDuplicateKeys.spec.ts
- src/utilities/checkDuplicateKeys.ts
This PR enables the same interpolation pattern with param support the the `host` part of a URL that we already support for `path` and `query`. 
Usage is exactly what you'd expect, you can define params as a plain string or with a new `host` utility.
```ts
const routes = createExternalRoutes([
name: 'foo',
host: 'https://[subdomain].kitbag.dev',
path: '/'
])
```
```ts
const routes = createExternalRoutes([
name: 'foo',
host: host('https://[subdomain].kitbag.dev', {subdomain: availableSubdomainsParam}),
path: '/'
])
```
as with other params
- they can be optional
- they support all the same type for params
- they can be passed when calling `router.resolve`, `router-link`, `router.push`, etc.
> added host utility, similar to path and query

- src/services/createExternalRoutes.spec.ts
- src/services/createRoutes.spec.ts
- src/types/externalRouteProps.ts
- src/types/path.ts
- src/types/routeProps.ts
Not sure why it took this long but I think `path` should have always been optional. This felt especially true when defining parent routes, or external routes
```ts
createExternalRoutes([
{
host: 'https://kitbag.dev',
path: '',
children: createExternalRoutes([
{
name: 'foo',
path: 'child',
},
]),
},
])
```
After this PR, path behaves like query. It's never required and when omitted is assumed to be an empty string.
```ts
createExternalRoutes([
{
host: 'https://kitbag.dev',
children: createExternalRoutes([
{
name: 'foo',
path: 'child',
},
]),
},
])
```
> make path optional

- docs/api/functions/createExternalRoutes.md
- docs/api/functions/host.md
- docs/api/functions/path.md
- docs/api/functions/query.md
- docs/api/types/ExternalRouteProps.md
- docs/api/types/RouteProps.md
- docs/core-concepts/defining-routes.md
With recent patch releases the docs has fallen slightly behind. This PR updates the topics for recent work.
- path is now optional on `routeProps` and `externalRouteProps`
- there was no documentation for external routes
- with external routes also comes new `host` utility
> updated docs for optional path, external routes, and host

- README.md
- docs/api/types/ParamGetSet.md
- docs/api/types/Route.md
- docs/core-concepts/defining-routes.md
- docs/core-concepts/navigating.md
- src/errors/routeDisabledError.ts
- src/services/createExternalRoute.ts
- src/services/createRoute.ts
- src/services/createRouterResolve.ts
- src/types/createRouteOptions.ts
- src/types/register.ts
- src/types/route.ts
- src/types/routesMap.spec-ts.ts
- src/types/routesMap.ts
with the latest iteration of defining routes we can now define parent routes and choose to not include them when calling `createRouter`. This effectively does the task of what "disabled" did previously but in a more straight forward and hopefully obvious way to our developers.
Currently, kitbag router lets you set a route as "disabled".  A disabled route still effects the children, passing down params, path, query, host, and key but a disabled route can never be matched. So end users cannot create a `router-link` to a disabled route or navigate with `router.push` to a disabled route.
```ts
const routes = createRoutes([
{ name: 'parent', disabled: true, children: createRoutes([
{ name: 'foo', component: ... },
{ name: 'bar', component: ... },
])
])
const router = createRouter(routes)
``` …
> remove disabled concept

- src/components/routerView.browser.spec.ts
- src/components/routerView.vue
- src/services/component.ts
- src/services/createExternalRoute.ts
- src/services/createRoute.ts
- src/services/paramValidation.spec.ts
- src/services/urlAssembly.spec.ts
- src/types/createRouteOptions.ts
- src/types/route.ts
To make the types for `createRoute` and `createExternalRoute` more intuitive I'm breaking apart `CreateRouteOptions` into more pieces and using those pieces directly within the overload declarations. This contrasts the current implementation where there are two type `CreateRouteOptionsWithoutParent` and `CreateRouteOptionsWithParent`.
We can now express options like `CreateRouteOptions & WithParent & WithComponent & ...` which makes each overload more intuitive and prevents some of the overlap between `createRoute` and `createExternalRoute`. For example, `host` is not an option when using `createRoute` and `component` is not an option when using `createExternalRoute`.
This also adds overloads and generics to `createRoute` specifically for component(s).
> Refactor types for creating routes and add overloads and generics to `createRoute` for component types

- src/components/routerView.vue
- src/services/createRoute.ts
We had logic in `createRoute` to add the `RouterView` component to any route that didn't have a component. But that would mean that `matched` and `matches` wouldn't directly reflect the users defined route options. 
Moving this logic into `RouterView` where we already have logic for getting the correct component to mount for a match.
> Move default component logic into `RouterView`

- src/errors/metaPropertyConflict.ts
- src/services/combineMeta.spec.ts
- src/services/combineMeta.ts
- src/services/createExternalRoute.ts
- src/services/createRoute.spec.ts
- src/services/createRoute.ts
- src/services/createRouter.ts
- src/services/createRouterReject.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/hooks.spec.ts
- src/types/createRouteOptions.ts
- src/types/resolved.ts
- src/types/route.ts
- src/types/state.ts
- src/utilities/testHelpers.ts
This PR updates `createRoute` utility to use a new `combineMeta` to merge child meta with parent (if parent exists). This follows the pattern used for state (and others).  Merging meta is just a bit unique in that duplicate keys are allowed as long as the child's property of the same name matches `typeof` for the parent. The thinking here being that the child can override the meta property of a parent.
This PR also adds a new test suite for `createRoute`, with tests for new meta functionality as well as combine logic for other parts of the route.
> merge parent route meta with children route meta

- src/components/index.ts
using "vue" instead of "@vue/runtime-core"
as described in vue docs
https://vuejs.org/guide/extras/web-components.html#web-components-and-typescript
not sure when this changed, but the language tools looks like it updated to support TS5.5
https://github.com/vuejs/language-tools/issues/4501#issuecomment-2190384987
> Fix declaration merging of GlobalComponents

- src/errors/routerRejectionError.ts
- src/services/createRouter.ts
- src/services/createRouterReject.ts
- src/types/hooks.ts
- src/types/register.ts
- src/types/router.ts
This PR should have no impact on the router at runtime. All it does is move the responsibility of defining rejection types from being part of the register interface
```ts
declare module '@kitbag/router' {
interface Register {
// router: typeof router
rejections: ['AuthNeeded']
}
}
```
into a generic captured by `createRouter`
```ts
const router = createRouter(routes, {
rejections: {
AuthNeeded: MyLoginComponent
}
})
```
If approved, will need a docs change before merging
> store rejections type in router

- src/services/createCurrentRoute.ts
- src/services/createRouterReject.ts
- src/services/hooks.ts
- src/services/isRejectionRoute.ts
while exploring the idea of "system" or "default" hooks to [handle scroll position](https://github.com/kitbagjs/router/issues/193) I found a couple bugs. 
- move `isRejectionRoute` out of createRouterReject, not used anyways
- ensure that `isRejectionRouteSymbol` defaults to `false` when updating current route. We use `Object.assign` to update current route. All non-rejection routes do not have this property. The initial current route is a rejection route (not found). So the property is there when we create the router and never gets unset. So every route appeared to be a rejection route
- we were taking `T extends Routes` on the hook runner methods but T was available from the parent function and wasn't being overridden.
> Minor fixes or rejection route type guard and types in hook runner methods

- src/components/routerView.browser.spec.ts
- src/components/routerView.vue
Because `route.params` wasn't actually accessed within the `component` computed property within `RouterView` so the effect wasn't tracked.
> Fix route props not being reactive when changing props on the current route

- docs/api/types/ResolvedRoute.md
- docs/api/types/RouterPush.md
- docs/api/types/RouterReplace.md
- docs/api/types/RouterResolve.md
- src/services/createRouterResolve.spec.ts
- src/services/createRouterResolve.ts
- src/services/createRouterRoute.ts
- src/services/getResolvedRouteForUrl.browser.spec.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/urlAssembly.spec.ts
- src/services/urlAssembly.ts
- src/types/resolved.ts
- src/types/routerPush.ts
- src/types/routerReplace.ts
This PR adds a missing core piece of the URL, the hash.
Previously, users could only set the hash by pushing with relative URL syntax with hash included
```ts
router.push('relative/foo#bar')
```
With this change, users can push (and replace) named routes with hash as part of the options
```ts
router.push('foo', {}, { hash: 'bar' })
```
This also works for `RouterLink`
```html
<router-link :to="resolve => resolve('foo', {}, {hash: 'bar'})">
```
And `useLink`
```ts
const { href } = useLink('foo', {}, { hash: 'bar' })
```
For reading the current hash value, this PR adds `{ hash?: string }` property to `ResolvedRoute`. Which means `route.hash` is available everywhere resolved routes are used.
```ts
const route = useRoute()
route.hash // string | undefined
```
In a future PR, I'd like to add …
> push/replace accepts option for hash, assembles on url

- src/services/combineHash.ts
- src/services/createExternalRoute.ts
- src/services/createRoute.spec.ts
- src/services/createRoute.ts
- src/services/getResolvedRouteForUrl.browser.spec.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/hash.ts
- src/services/routeMatchRules.spec.ts
- src/services/routeMatchRules.ts
- src/services/routeMatchScore.ts
- src/services/urlAssembly.ts
- src/types/createRouteOptions.ts
- src/types/hash.ts
- src/types/route.ts
- src/types/routeWithParams.spec-d.ts
This PR introduces a type and service for Hash similar to `Path`, `Query`, and `Host`. Each of these parts of the url can be defined when calling `createRoute`. It's normalized from `string | undefined | Host` on `Route` and is combined down from parent routes to children routes. Host is checked for route matching rules, route scoring (for multiple matches), and is used when assembling a URL for a given route. 
Some places where `Host` is different
- Host doesn't currently have any params, so there are no `param` on the host type
- The Host type also adds `hasValue: () => boolean` to the type. I found this useful because host will insert "#" only when there is a value that passes `stringHasValue` check. 
- Users can use the `host` utility when calling `createRoute` but it won't offer any …
> Hash on route definition

- src/services/combinePath.ts
- src/services/combineQuery.ts
- src/services/createRoute.spec.ts
- src/services/host.ts
- src/services/path.ts
- src/services/query.ts
- src/types/host.ts
- src/types/path.ts
- src/types/query.ts
When I created the `hash` utility I decided to use `hash.value` instead of `hash.hash` like we have on `path`, `host`, and `query`. It felt like a better name for the property that holds the string value of each. 
This PR updates `path`, `host`, and `query` to use "value" for this property to avoid `route.path.path`, `route.host.host`, and `route.query.query`.
Should have no impact on devex or actual router behavior
> updated syntax on url types to use `value`

- src/components/routerView.browser.spec.ts
- src/services/component.browser.spec.ts
- src/services/component.ts
When working on https://github.com/kitbagjs/router/pull/278 I noticed some `Suspense` warnings.
```
<Suspense> is an experimental feature and its API will likely change.
```
I started out attempting to just silence these. But researching more I'm not sure we even need to use suspense. You do not need to use suspense for async components. Its optional and only needs to be used for loading/error states. 
You do however seem to need `Suspense` when using `async setup`. Which we were using in the `AsyncPropsWrapper`. But we don't have to. Rewriting that component to not need top level await removes the need for `Suspense` altogether. 
I'm not 100% sure if this removes the possibility for leveraging `Suspense` for loading states. But we haven't really proved out some of those ideas around …
> Remove requirement on `<Suspense>`  for async component props

- docs/api/types/Router.md
- src/components/routerLink.browser.spec.ts
- src/components/routerView.browser.spec.ts
- src/compositions/useRoute.browser.spec.ts
- src/services/component.browser.spec.ts
- src/services/createRouter.browser.spec.ts
- src/services/createRouter.spec.ts
- src/services/createRouter.ts
- src/types/router.ts
Because global hooks need to be defined on the router AFTER it is created it is problematic that the initial route is set immediately on creation. This can cause race conditions and import issues with other modules. 
By replacing the `initialized` property of the router with a `start` method and then automatically calling `start` when the router is installed we can make sure that the user is able to define global hooks and have them run on that initial route while avoiding module errors. 
Closes https://github.com/kitbagjs/router/issues/269
> Delay initializing the router until it is installed or manually started

- src/components/routerLink.browser.spec.ts
- src/components/routerLink.vue
- src/compositions/useLink.ts
Since `useLink` should contain everything necessary to create a link without using `router-link` I'm moving more of the logic from `router-link` into `useLink`. This makes `useLink` more useful and `router-link` simpler.
> Abstract more of router-link into useLink

- src/components/routerView.vue
- src/services/createPropStore.ts
- src/services/createRouter.ts
- src/types/prefetch.ts
this PR is my pass at solving the same problems as [this PR](https://github.com/kitbagjs/router/pull/281).
most notably
- moves from an option `prefetch: true` to separate methods because the implementations are considerably different
- updates the store type to put `prefetched: true` on each store entry
- ensures that matches that have `prefetch: false` in their route definition will not be prefetched even when the parent tries to
> Update prop store to support prefetching

- src/components/routerLink.browser.spec.ts
- src/compositions/useLink.ts
- src/types/prefetch.ts
Adds the ability to prefetch props for routes. This follows the same config as component prefetching but is disabled by default.
This allows for props to be loaded prior to a route being visited so that when a router-link is clicked the props are already loaded (or have at least already started loading). 
```ts
const route = createRoute({
name: 'user',
path: '/users/[userId]',
prefetch: { props: true },
component: UserView,
props: async ({ userId }) => {
const response = await fetch(`/api/users/${userId}`)
const user = await response.json()
return { user }
},
})
```
You can also set prefetch at the router or the router-link level same as for components.
> Prefetching route component props

- src/compositions/useLink.ts
- src/compositions/usePrefetching.ts
Gives us a place to iterate on prefetching logic. Keeps `useLink` clear of prefetching logic. 
Duplicate of https://github.com/kitbagjs/router/pull/288
> Add `usePrefetching` composition to abstract prefetching logic out of `useLink`

- docs/advanced-concepts/route-matching.md
- docs/api/components/RouterLink.md
- docs/api/types/Route.md
- docs/core-concepts/defining-routes.md
- docs/core-concepts/navigating.md
With recent PRs adding `hash` functionality to Kitbag Router
- https://github.com/kitbagjs/router/pull/265
- https://github.com/kitbagjs/router/pull/267
Our documentation was lacking this important information
> add missing docs for hash on route definition

- src/services/createRouterReject.ts
when testing the usability of `route.matches`, I came up with the following test case
```ts
import { Url, isUrl, useRoute, useRouter } from '@kitbag/router';
import { computed } from 'vue';
const router = useRouter()
const route = useRoute()
function isRouteName(name: string | undefined): name is typeof route['name'] {
return !!name && name !== 'NotFound'
}
const matches = computed(() => {
return route.matches.reduce<Url[]>((matches, match) => {
if(isRouteName(match.name)){
const url = router.resolve(match.name, route.params)
if(isUrl(url)){
matches.push(url)
}
}
return matches
}, [])
})
```
You'll notice how my `isRouteName` had to check that the name existed AND was not the rejection route. This feels wrong, and would not continue to work if additional rejection types were added. …
> remove match name from rejection route

- src/services/insertBaseRoute.spec.ts
- src/services/insertBaseRoute.ts
closes #302 
when `base` is supplied, the router acts as though the user created a parent above all other routes. When it's re-creating the rest of the routes, it was incorrectly passing in the `Route` type (from router) and not the `route.matched`, which is the options the user would have supplied when calling `createRoute`.  
Note, because there are so many overloads, the type is unhappy and I didn't want to mess with it right now 😄
> fix bug with router base

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/services/createResolvedRouteQuery.ts
- src/services/createRouter.spec.ts
- src/services/createRouterRoute.ts
- src/services/hooks.spec.ts
- src/services/paramsFinder.spec.ts
- src/types/resolvedQuery.ts
- vite.config.js
`URLSearchParams` is a really nice interface for working with the query. But it cannot be accurately proxied which is how we trigger updates to the route in `RouterRoute`. But we can get 99% of the nice devX by wrapping `URLSearchParams` in a normal object that just aliases all the members. The only things that don't work with this are
- You cannot pass `ResolvedRouteQuery` into the constructor of `URLSearchParams`. But you can easily work around with by passing `query.toString()`
- You cannot directly iterate over the query like you could with `URLSearchParams`. But iterating over `query.values()` provides the same functionality. 
This PR adds all of the missing members to the `ResolvedRouteQuery` type and updates the `RouterRoute` to trigger route updates when `set`, `append`, or …
> Update route.query to support all members of `URLSearchParams` and make the query writable on `RouterRoute`

- docs/.vitepress/config.ts
- docs/api/components/RouterLink.md
- docs/api/types/QuerySource.md
- docs/api/types/RouterPush.md
- docs/api/types/RouterReplace.md
- docs/api/types/RouterResolve.md
- src/services/createRouter.spec.ts
- src/services/createRouterResolve.ts
- src/services/createRouterRoute.ts
- src/services/routeMatchScore.ts
- src/services/urlAssembly.ts
- src/types/query.ts
- src/types/routerPush.ts
- src/types/routerReplace.ts
- src/utilities/urlSearchParams.spec.ts
- src/utilities/urlSearchParams.ts
We discovered [in a recent PR](https://github.com/kitbagjs/router/pull/308) that the type we're using to pass query values (`Record<string, string>`) was limiting our ability to mirror native behavior of built in `URLSeachParams` type. Specifically, the object syntax doesn't allow for multiple entries with the same key.
This PR updates our `QueryRecord` type to match any value accepted by the constructor of `URLSeachParams`.
> Extend query support to match URLSeachParams

- src/services/createRouter.spec.ts
- src/services/createRouterRoute.ts
https://github.com/kitbagjs/router/pull/309 Make it possible to modify the query directly via the route. But making multiple operations makes multiple `push` calls. You could call `route.update({}, { query: newQuery })` but since we already have the mechanisms to make parts of the route writable we can allow users to assign the query as a nice syntax that is a better devx. 
This PR makes this possible
```ts
const route = useRoute()
route.query = 'foo=bar'
// or any other QuerySource such as URLSearchParams
route.query = new URLSearchParams({ foo: 'bar' })
```
> Make `route.query` assignable so the entire query can be replaced

- src/services/createRouter.spec.ts
- src/services/createRouterRoute.ts
- src/types/utilities.ts
Sugar around `route.update({ foo: 'bar', fuz: 'buz' })` to make it possible to just write
```ts
route.params = { foo: 'bar', fuz: 'buz' }
```
> Make route.params assignable so all params can be replaced

- package-lock.json
- package.json
- src/services/createRouter.spec.ts
- src/services/createRouterRoute.ts
We've been proxying the entire route object and using get/set traps to add functionality to certain properties. But that's getting unwieldily because the get and set traps force the logic for a single property to be split up. Using vue's native computed properties makes this much simpler for top level properties. We'll continue using proxies for individual params and for query methods that modify the query.
> Refactor `RouterRoute` to use computed properties for `params`, `query`, and `state`

- src/compositions/useQueryValue.browser.spec.ts
- src/compositions/useQueryValue.ts
- src/services/params.ts
Query params are useful for route matching and declaring known route state. But sometimes the query state cannot be known ahead of time, is dynamic, or for other reasons cannot be declared on the route. 
`useQueryValue` aims to make working with query values that are not params as feature rich as params themselves. 
Working with simple values
```ts
const { value } = useQueryValue('foo')
//           ?^ Ref<string | null>
```
Working with arrays
```ts
const { values } = useQueryValue('foo')
//           ?^ Ref<string[]>
```
Using params
```ts
const { value, values } = useQueryValue('foo', Number)
value // Ref<number | null>
values // Ref<number[]>
```
A `remove` callback is also returned to make deleting query keys simple
```ts
const { value, remove } = useQueryValue('foo')
value.value = …
```
> `useQueryValue` composition to make working with query values that are not params just as easy

- src/compositions/useQueryValue.browser.spec.ts
Tidying up these vue warnings from `useQueryValue` tests
> Fix vue warnings around invalid templates in `useQueryValue` tests

- src/services/hooks.ts
No functional change, but now that we have route ids it seems like we should use those here rather than comparing object references.
> Use route ids for hook conditions

- docs/core-concepts/component-props.md
- src/components/routerView.browser.spec.ts
- src/services/createPropStore.ts
- src/services/createRoute.ts
- src/types/createRouteOptions.ts
Previously the props callback when creating a route passed just the params for the route in as the first argument. But there are lots of useful pieces on the route itself such as the query, hash, state, etc. Passing in the entire route offers much more functionality. 
**This is a breaking change**
Any uses of the props callback will need to change from 
```ts
createRoute({
...,
props: (params) => {
return { value: params.foo }
}
})
```
to
```ts
createRoute({
...,
props: (route) => {
return { value: route.params.foo }
}
})
```
Closes https://github.com/kitbagjs/router/issues/340
> Pass the entire resolved route rather than just the params

- src/services/createRouter.ts
@hagabaka found that after using the browser back, the rest of history would be lost. The issue was not using `replace: true` when the history listener fires inside createRouter.
> Fix losing history on browser back

- src/services/urlAssembly.spec.ts
- src/services/urlAssembly.ts
Back in https://github.com/kitbagjs/router/pull/310, we extend route query support to match `URLSeachParams`. This switched from merging 2 deconstructed objects into a `for of` loop of `search.entries()`. However I discovered in our router-preview which has a `key` page with 2 optional query params and in the first iteration of `search.entries()` it found a key to delete. When it deleted it, it also updated the source of the loop, and ended up exiting the `for of` seeing only 1 total entry now.
> fixed bug with urlAssembly of query

- src/services/createPropStore.ts
- src/types/createRouteOptions.ts
- src/types/hooks.ts
- src/types/props.ts
Prop callbacks were incorrectly being passed the `abort` callback. Fetching props is not a blocking operation so navigation cannot be aborted.
> Update the types for prop callback context to remove `abort`

- src/guards/routes.spec-d.ts
- src/guards/routes.ts
- src/types/route.ts
Fixes a bug with the `isRoute` type guard where non exact matches were not being correctly narrowed.
> Fix isRoute return type for non exact matches

- README.md
- docs/advanced-concepts/hooks.md
- docs/advanced-concepts/prefetching.md
- docs/advanced-concepts/route-state.md
- docs/api/functions/createRouter.md
- docs/core-concepts/defining-routes.md
- docs/getting-started.md
When defining an array of routes its important to use `as const` otherwise the type returned by `createRouter` won't be as useful
> Make sure docs use `as const` when necessary

- src/components/routerLink.browser.spec.ts
- src/compositions/usePrefetching.ts
- src/utilities/components.ts
Prefetching components using a `lazy` strategy was throwing this error
```
TypeError: Cannot read properties of null (reading 'ids'
```
This was because to prefetch components we had been calling `setup` manually on vue's AsyncComponentWrapper component. However the setup for AsyncComponentWrapper requires a component context to hook up suspense functionality. So calling setup outside the router link's component setup (when the lazy strategy is executed) there was no instance. 
Fixing this by calling the [loader function](https://github.com/vuejs/core/blob/201936f9a3909ae9dca4e131e1f5ad5a1c0feb77/packages/runtime-core/src/apiAsyncComponent.ts#L121) directly.
> Fix prefetching components with strategy `lazy` throwing component context error

- docs/advanced-concepts/transitions.md
- src/services/createRouterReject.ts
- src/services/createRouterRoute.ts
- src/services/getResolvedRouteForUrl.ts
- src/services/hooks.spec.ts
- src/types/resolved.ts
- src/utilities/testHelpers.ts
this is step 1 of a couple different initiatives.
1.) we need a key that's unique to handle transitions when params change, currently using `route.id` but that won't change when params change. With this new `href` property, we will have a better candidate. (this is really just a 1 line docs change, so I decided to commit it here)
2.) we want to avoid "widening" the route inside of RouterLink, currently users might use an explicit route name as part of the `ToCallback` which uses RouterResolve and returns a Url. Once we "widen" from an explicit route name to a Url, we've found that will sometimes actually point to a different route now, causing a bad DX and confusion.
> add "href" property to ResolvedRoute

- src/compositions/usePrefetching.ts
- src/compositions/useVisibilityObserver.ts
Since `useLink` can be used to create custom link elements, its possible the element template ref won't be available on mount or that it might be dynamic. Updating `useVisibilityObserver` to be more resilient to changes to the element template ref
> Update `useVisibilityObserver` to be reactive to ref changes

- src/components/routerLink.browser.spec.ts
Adds a test to make sure that even when there are two routes with the same url and a link is created that the route specified by the resolve is used.
> Add a test to ensure the exact resolved route is used for `router-link`

- src/components/routerLink.browser.spec.ts
- src/components/routerView.browser.spec.ts
- src/services/component.browser.spec.ts
normalize to `wrapper` > `app`
> coalescing around "wrapper" for mounted const in tests

- src/services/createRouterReject.ts
- src/services/hooks.spec.ts
- src/types/resolved.ts
- src/utilities/testHelpers.ts
this actually created an issue with reactivity inside `createCurrentRoute`, or at least that's my theory
we create our reactive with
```ts
const route = reactive({ ...fallbackRoute })
```
which is later updated with
```ts
const updateRoute: ResolvedRouteUpdate = (newRoute) => {
Object.assign(route, {
[isRejectionRouteSymbol]: false,
...newRoute,
})
}
```
when fallbackRoute doesn't have `hash`, calling updateRoute with a newRoute with a hash was NOT assigning hash to `router.route.hash`.
> hash should always be populated in ResolvedRoute

- src/services/state.ts
ran into this issue while working on https://github.com/kitbagjs/router/pull/371
There was nothing handling `getStateValue` when `state` is a record, and the value at `key` is not a string. I'm pretty sure this happens when we call `createResolvedRoute` and the state we provide is already in the type the state expects like `zoo: 123`.
> fix bug with getStateValue

- src/types/register.ts
Fixes an issue where even though custom rejections were passed when creating a router, and then that router was registered, the custom rejections would not show up when using `router.reject`
> Fix custom rejections not being inferred from the registered router

- src/types/register.spec.ts
- src/types/register.ts
- src/types/router.ts
We had reports of registered rejections having the wrong type in [Kitbag's Discord](https://discord.gg/zw7dpcc5HV). 
We've traced the type issue down to using Vue's `Plugin` type as part of the `Router` definition. This PR removes that (while still satisfying the ObjectPlugin syntax). This PR also adds some type tests around some of the common Register types used often.
> remove plugin from Router, add Register tests

- src/compositions/useVisibilityObserver.ts
Fixes an issue where any link that is mounted is still observed even after it has been unmounted.
> Make sure elements are no longer observed when unmounted

- src/services/createRouter.ts
This was how I originally intended to write this but at the time `Promise.withResolvers` wasn't working because of a missing ts lib. That has since been fixed so fixing this up so even if you call `start(); start()` it won't actually execute twice.
> Make sure start cannot be called multiple times

- src/compositions/hooks.ts
- src/compositions/useRoute.browser.spec.ts
- src/services/createRouter.spec.ts
- src/services/createRouter.ts
- src/services/createRouterHooks.ts
- src/services/createRouterPlugin.browser.spec.ts
- src/services/createUniqueIdSequence.ts
- src/services/getGlobalHooksForRouter.ts
- src/services/getGlobalRouteHooks.ts
- src/services/getRouteHooks.ts
- src/services/hooks.ts
- src/types/hooks.ts
- src/types/router.ts
- src/utilities/testHelpers.ts
This PR fixes both hooks related issues outlined in https://github.com/kitbagjs/router/issues/402
**Global Hooks**
Now when global hooks are registered they are registered without conditional wrappers based on depth. That way when hooks are gathered they can be gathered based on what route navigation is actually happening (enter, update, or leave) no matter at what level. 
This means that if any of the matches are an enter then each global route enter hook will be executed once. Same for update and leave. 
**Update hooks on first navigation**
Since the `NotFound` rejection route is always the starting point for the route, when hooks were executed for the first navigation (when the router was started) the `from` context would have a route. This would cause global `leave` hooks to be …
> Update global hooks to not be based on root routes and fix `from` on router start

- src/services/urlAssembly.spec.ts
- src/services/urlAssembly.ts
we store params as they're supplied by the user, so optional params will include the `?`.
```ts
query: {
value: 'foo=[?foo]`,
params: {
'?foo': String
}
}
```
When calling param setter while assembling a url, we were expecting to find the param by the `paramName` which does not include `?`. This was hard to notice before because when no param is found, the router falls back on `toString()` which was satisfying every test we had. (now we have a more specific test)
This was also only effecting query because path and host iterate via `Object.entries(path.params)`, so key includes `?`. Query is setup slightly differently because we build a new `URLSearchParams` object from scratch. This enables us to completely omit a search value if it's not provided and optional.
> make sure we find corresponding param when setting query values

- src/services/paramValidation.spec.ts
- src/services/paramValidation.ts
- src/services/urlAssembly.spec.ts
closes #415 
First thought was this was probably related to recent change to [urlAssembly](https://github.com/kitbagjs/router/pull/412/files). I wrote a test that asserts expected behavior when param name is different from query key.
```ts
// src/services/urlAssembly.spec.ts
test('given route with query params with different param names than query keys, still works as expected', () => {
const route = createRoute({
name: 'query-keys',
path: '/',
query: 's=[?search]',
})
const url = assembleUrl(route, { params: { search: 'foo' } })
expect(url).toBe('/?s=foo')
})
```
That test already passes in main, but I included in this PR to ensure expected behavior moving forward.
urlAssembly is looking for params and calling `setParamValue`. This lead me to paramValidation which is the inverse, it …
> fix bug with get query params with different keys

- src/routeProps.spec.ts
- src/services/createPropStore.ts
Because of a bad for loop the props store wasn't actually clearing out props from previous navigations. This meant that if you re-navigated to the same route the props wouldn't be run again.
> Fix route props not clearing after navigation happens

- src/services/createPropStore.ts
- src/services/createRoute.spec-d.ts
- src/services/createRoute.spec.ts
- src/types/createRouteOptions.ts
- src/types/props.ts
When parent routes have props, it can sometimes be useful to reuse one or more values in the props of the child route. This allows for sharing values across routes without duplicating the logic and also enables data dependent props where the child determines its props based the props value(s) from the parent. 
**sync props**
```ts
const parent = createRoute({
name: 'parent',
}, () => ({ foo: 123 }))
const child = createRoute({
name: 'child',
parent: parent,
path: '/child',
}, (__, { parent }) => ({
propFromParent: parent.props.foo
}))
```
**async props**
```ts
const parent = createRoute({
name: 'parent',
}, async () => ({ foo: 123 }))
const child = createRoute({
name: 'child',
parent: parent,
path: '/child',
}, async (__, { parent }) => {
const { foo } = await parent.props
return { …
```
> Add `parent` context with name and prop values to the callback context of route props

- src/services/host.ts
- src/services/params.spec.ts
- src/services/params.ts
- src/services/path.ts
- src/services/query.ts
- src/tests/routeProps.spec.ts
- src/types/paramTypes.ts
- src/types/params.ts
- src/types/routeWithParams.ts
With this PR we're extending the possible param types to include literal values for `string | number | boolean`.
```ts
const example = createRoute({
name: 'example',
path: path('/[foo]' { foo: 14 })
})
```
This means when you supply a value for the `foo` param, it must be exactly the literal number `14`. The same works for literal strings and booleans.
By itself, this feature doesn't provide much real world value to users.  If you had a literal value in mind for a param it's not exactly dynamic, which is the whole point of params in your url. However, we're collaborating on some exciting new utilities for `oneOf`, `anyOf`, and `allOf` which will expect an array of `Param`.
> add support for literals as param types

- src/types/params.ts
- src/types/resolved.spec-d.ts
- src/types/routeWithParams.ts
when we introduced [Literal Types](https://github.com/kitbagjs/router/pull/434) we discovered 2 types that were almost identical. This PR cleans that up so 1 uses the other.
As a side question this PR also improves a test that had a super loose param type.
> Unify extract param type types

- src/components/echo.ts
- src/components/routerView.vue
- src/compositions/useComponentsStore.ts
- src/services/component.browser.spec.ts
- src/services/component.ts
- src/services/createComponentsStore.ts
- src/services/createRouter.ts
- src/tests/routeProps.browser.spec.ts
This approach builds on what I learned in https://github.com/kitbagjs/router/pull/439 and fixes the remounting of components when params change. What this does differently is it uses a factory to create a wrapper around the route's component that handles the prop binding, suspense, and async updates. And it stores that wrapper in a store so that it can be reused.
> Fix route components remounting rather than being updated when props change

- src/services/ zod.spec.ts
- src/services/createRouter.ts
- src/services/params.ts
- src/services/zod.ts
- src/types/paramTypes.ts
- src/types/routeWithParams.ts
https://github.com/kitbagjs/router/pull/446 introduced experimental support for zod params. However it didn't account for zod not being installed even though its clearly marked as an optional param. 
In order to account for this we can use an asyn import and only import actual zod code if we detect that a zod param is being used
> Make sure zod isn't required if zod params are not being used

- src/services/createParam.ts
in the router-preview project we have the following custom param
```ts
import { createParam } from "@kitbag/router"
type SortDirection = 'asc' | 'desc'
function isSortDirection(value: unknown): value is SortDirection {
return !!value && typeof value === 'string' && ['asc', 'desc'].includes(value)
}
export const sortParam = createParam((value, {invalid}) => {
if(isSortDirection(value)){
return value
}
throw invalid(`value provided does not satisfy `)
}, 'asc')
```
with any version of Kitbag router after we added [LiteralParams](https://github.com/kitbagjs/router/pull/434), we get the following error
Simply adding `NoInfer` around the default value seemed to do the trick 🎉
> narrow the types of Param that can be sent to createParam

- src/types/params.ts
- src/types/resolved.ts
- src/types/route.spec-d.ts
- src/types/routeWithParams.ts
- src/types/state.ts
Currently there are some "extract param types" types were responsible for both finding out what type a param should be and also based on the key determining if the type should include `| undefined`. This PR moves that 2nd responsibility out into a separate type and also just aims to clean up the two similar but different extract types.
This needs to manual testing. I did a little testing and obviously the minimal type tests we have are passing but it would be easy to miss something that should have `| undefined` and doesn't or vice-versa.
> simplify extract param type, move check for optional

- src/services/insertBaseRoute.ts
Fixes an issue with base paths where the path was not properly stringified
> Fix insertBaseRoute stringifying `path` and not `path.value`

- src/services/paramValidation.ts
in a [previous PR](https://github.com/kitbagjs/router/commit/caecf3e76a43287fc4d26558a1a5fc7ec3a6781a#diff-56f61b45256cb6dd3fc0a966c28a11f79b10821217a99a2cb8931d9224a9844d) we over-simplified the process of getting param values out of different parts of the URL. There are unique responsibilities of the function that gets values from the query.
1. Find query values when other query params are omitted or in a different order
2. Find query values based on the url search key, which might not match the param name
> return unique method for finding param values in the query

- package.json
- src/services/combineHash.spec.ts
- src/services/combinePath.spec.ts
- src/services/combineQuery.spec.ts
- src/services/params.ts
when we [unified our param utilities into withParams](https://github.com/kitbagjs/router/pull/447), we also changed the logic for the combine utilities like `combinePath`, `combineQuery`, etc. Those utilities used to just spread the params together
```ts
return {
value: newPathString,
params: { ...parentPath.params, ...childPath.params },
}
```
But with the half thought of a `toString()` method I updated this to re-call `withParams`
```ts
return withParams(newPathString, { ...parentPath.params, ...childPath.params })
```
Even without the `toString()` property this felt right but caused a bug. Because `withParams` renames param keys to possibly start with a leading "?" it ends up being lost when we re-call `withParams` when combining. Therefore if you assign a custom param (anything other …
> Fix combine bug

- docs/advanced-concepts/hooks.md
- docs/core-concepts/component-props.md
- src/services/createPropStore.ts
- src/services/createRouter.ts
- src/services/createRouterHooks.ts
- src/services/hooks.spec.ts
- src/tests/hooks.spec.ts
- src/tests/routeProps.spec.ts
- src/types/hooks.ts
- src/utilities/props.ts
- src/utilities/runWithContext.ts
Since 3.3 vue has had a utility called [runWithContext](https://vuejs.org/api/application.html#app-runwithcontext) which allows for global injection to work within any callback. Using this when running hooks and props means that global injection also works within those callback. 
```ts
import { inject } from 'vue'
router.onAfterRouteEnter((to, context) => {
const value = inject('global')
...
})
```
```ts
import { inject } from 'vue'
const route = createRoute({
...
}, async (route) => {
const value = inject('global')
return { value }
})
```
> Run hooks and props within the context of the vue app

- src/services/combinePath.ts
- src/services/combineQuery.ts
- src/services/withParams.ts
- src/types/RouterResolve.ts
- src/types/params.ts
- src/types/resolved.spec-d.ts
- src/types/resolved.ts
- src/types/route.spec-d.ts
- src/types/routeWithParams.ts
- src/types/state.ts
when we [simplified the extract type logic](https://github.com/kitbagjs/router/pull/455), we de-duped the ExtractType logic from src/types/routeWithParams.ts so now there are 2 types in src/types/params.ts. The types are `ExtractParamTypes` and `ExtractParamTypesWithOptional`. When testing some params I had the following test case
```ts
const keys = createRoute({
parent: settings,
name: 'settings.keys',
path: '/keys',
query: withParams('sort=[?sort]', { 
sort: withDefault(unionOf('asc', 'desc'), 'asc') 
}),
component: defineAsyncComponent(() => import('../views/SettingsKeysView.vue'))
})
```
and I found that when I tried pushing to `settings.keys` it was expecting `sort` to be passed because our logic in `ExtractParamTypesWithOptional` says if an optional param has a default, it should …
> Type bug assigning params with default

- src/services/combineHash.spec.ts
- src/services/combinePath.spec-d.ts
- src/services/combinePath.spec.ts
- src/services/combinePath.ts
- src/services/combineQuery.spec.ts
- src/services/combineQuery.ts
- src/services/createExternalRoute.ts
- src/services/getParamsForString.ts
- src/services/paramValidation.ts
- src/services/params.ts
- src/services/paramsFinder.spec.ts
- src/services/paramsFinder.ts
- src/services/routeMatchScore.spec.ts
- src/services/routeMatchScore.ts
- src/services/routeRegex.spec.ts
- src/services/routeRegex.ts
- src/services/urlAssembly.ts
- src/services/withParams.spec-d.ts
- src/services/withParams.ts
- src/types/params.ts
- src/types/resolved.ts
- src/types/route.spec-d.ts
- src/types/routeWithParams.ts
- src/types/state.ts
- src/utilities/checkDuplicateKeys.ts
Currently, anything that can have params is normalized to `WithParams` type. This type has a `params` property that stores `Record<string, Param>`. The key for each param is where we store if we expect the param to be optional or not.
For example: 
```ts
{ value: '/[foo], params: { "foo": Boolean } }
```
This `WithParams` has a single param "foo", which we can see is **NOT** optional.
```ts
{ value: '/[?foo], params: { "?foo": Boolean } }
```
Versus this `WithParams`, where "foo" is now optional.
We've never loved sticking the leading "?" in the params object for several reasons
- it's ugly
- it's changing the keys as defined by the user
- when we check for duplicate param names we need to look for the same name in twice where one has the question mark
- we combine two `withParams` …
> alt approach to knowing what params are optional

- src/services/arrayOf.spec.ts
- src/services/arrayOf.ts
- src/services/tupleOf.spec.ts
- src/services/tupleOf.ts
- src/services/unionOf.spec.ts
- src/services/unionOf.ts
in a [recent PR](https://github.com/kitbagjs/router/pull/436) we introduced 3 new param utilities
`arrayOf`, `tupleOf`, and `unionOf`
This PR modifies the call signature of these utilities to accept an array of param types as the 1st argument instead of spreading the argument. This allows for a 2nd argument to be specified for "options".
As of right now, array and tuple are the only ones that accept options, and their options are identical.
```ts
type options = {
separator?: string,
}
```
This allows users to override the default behavior of the utilities to choose their own separator instead of the default comma `","`.  For example, users might choose a pipe `"|"` which changes the url from
> https://ticketing.service.dev?category=music,sports,art
to be
> …
> update param utilities to accept options, separator for arrays

- src/services/createExternalRoute.ts
- src/services/withParams.ts
- src/types/createRouteOptions.ts
quite awhile ago, we greatly [simplified the types for overloads in createRoute](https://github.com/kitbagjs/router/pull/421). I noticed that our types for overloads in `createExternalRoute` never got the same treatment. This PR addresses that and keeps the 2 utilities working more or less the same.
> make types for createExternalRoute more like createRoute

- .github/dependabot.yml
I believe this will make dependabot open a single PR with multiple dependencies. That way the tests can run once and they can all be merged. This will be a lot easier to maintain vs the many individual prs.
> Add some dependabot groups for dev dependencies

- package-lock.json
- package.json
- src/services/valibot.spec-d.ts
- src/services/valibot.ts
- src/services/zod.spec-d.ts
- src/services/zod.ts
- src/types/params.ts
Should fix type issues around valibot params
> Fix valibot params causing `Param` to be type `any`

- src/components/routerLink.browser.spec.ts
- src/components/routerLink.vue
- src/compositions/useLink.ts
- src/utilities/guards.ts
The `isMatch` and `isExactMatch` properties of `useLink` and `router-link` give users insight into whether or not the link's route matches the current route based on the actual route definitions. This means for the route `/posts/[postId]` both `/posts/foo` and `/posts/bar` are exact matches if the current route is `/posts/baz`. and `/posts` is a match for all three. 
These aren't very useful when trying to determine if a link is the same as the current routes href (the url the user sees). 
Introducing `isActive` and `isExactActive` to address this. These properties focus on the hrefs/urls themselves. So in the posts example, if the current url is `/posts/baz`
| Link | Active | Exact Active |
|----------|----------|----------|
| `/posts/foo`   | false    | false     |
| `/posts/bar`   | …
> Add classes and slot scope for "active" links

- src/components/routerView.browser.spec.ts
- src/components/routerView.vue
- src/services/createRouter.ts
- src/types/router.ts
Taeling reported in discord that when they added transitions to their router view the "NotFound" text was being shown first before the matched route was shown. 
This was happening because
A) The default route is the not found route
B) The router view renders immediately
C) The router itself is started asynchronously
> Fix "NotFound" flashing when using transitions

- src/components/routerView.spec.ts
- src/components/routerView.vue
Because the router's initialization is async the router view won't render anything when the vue app first starts. In we rely on reactivity to automatically render the route component when the router is finished initializing. But when doing SSR we need to make sure the router is initialized BEFORE we attempt to render anything. Leveraging `onServerPrefetch` let's vue know to wait to render the router view component until the router is finished initializing.
> Make sure router view waits for the router to be started when doing SSR

- src/compositions/index.ts
This composition was not in the compositions barrel so it was not exported as part of the public api. 
Closes #540
> Export useQueryValue composition

- .vscode/settings.json
- src/guards/routes.spec-d.ts
- src/services/createRoute.spec-d.ts
- src/services/unionOf.ts
- src/types/params.ts
- src/types/register.spec.ts
- src/types/resolved.spec-d.ts
Noticed that `toMatchTypeOf` was deprecated. Updated to using `toEqualTypeOf` which is more accurate and also found a bug in `ExtractParamType` where it would return `any` when it should return `undefined` in cases where the generic `Param` was passed.
> Update type tests and fixes `ExtractParamType` returning `any`
