src/types/routeMethods.ts

Simple type for what RouteMethod will return

Add types for what a RouteMethod returns

---

src/.eslintrc
src/compositions/useRoute.ts
src/compositions/useRouteParam.ts
src/compositions/useRouteParamRaw.ts
src/types/routeMethods.ts
src/utilities/random.ts

- updates rules to disabled @typescript-eslint/no-explcit-any
- ran `npm run lint:fix`
- updated `{}` to `object` in routeMethods `ExtractParamsFromPath` type

fixed _most_ lint warnings

---

src/compositions/useRoute.ts
src/types/routeMethods.test-d.ts
src/types/routeMethods.ts

Update the expected return type for a RouteMethod

Update the RouteMethod and RouteMethodRoute types

---

src/.eslintrc
src/components/index.ts
src/components/routerLink.browser.spec.ts
src/components/routerLink.ts
src/components/routerView.ts
src/compositions/useRouter.ts
src/utilities/createRouter.ts

Most basic implementation. Several things this doesn't account for. But seems to work as expected for basic rendering and clicking.

Implement RouterLink component

---

src/types/resolved.ts
src/utilities/resolveRoutes.spec.ts
src/utilities/resolveRoutes.ts

to be used as part of "scoring" possible route matches

add depth: number property to resolved routes

---

src/components/index.ts
src/components/notFound.ts
src/components/routerView.browser.spec.ts
src/components/routerView.ts
src/compositions/index.ts
src/compositions/useRejection.ts
src/compositions/useRouter.ts
src/types/middleware.ts
src/types/register.ts
src/types/router.ts
src/utilities/createRouter.browser.spec.ts
src/utilities/createRouter.ts
src/utilities/createRouterReject.ts

Adds types and support for rejections and implements the NotFound rejection type.

Rejections

---

src/types/routePaths.ts
src/types/routeWithParams.ts
src/utilities/createRouter.ts

Doesn't fix the single route issue but fixes a few other things and cleans up some types a big.

Update RouteWithParam types

---

src/types/routeMethod.ts
src/types/router.ts
src/utilities/createRouter.ts
src/utilities/createRouterReplace.ts

Pretty simple. Cleans up some types and pulls more out of createRouter and Routes.ts

Add a createRouterReplace utility and update types

---

src/components/routerView.browser.spec.ts
src/types/middleware.ts
src/types/utilities.ts
src/utilities/createRouter.ts
src/utilities/createRouterReject.ts
src/utilities/createRouterRoute.ts
src/utilities/middleware.ts
src/utilities/routes.ts

Continuing on the ideas/progress from https://github.com/kitbagjs/router/pull/79

rearrangement suggestion suggestions

---

src/utilities/paramValidation.spec.ts
src/utilities/paramsFinder.ts
src/utilities/routeMatch.browser.spec.ts
src/utilities/routeMatchRegexRules.browser.spec.ts
src/utilities/routeRegex.spec.ts
src/utilities/routeRegex.ts

disallow forward slash in matching route params and when validating route param values

Params disallow forward slashes

---

src/types/errors.ts
src/utilities/createRouter.ts
src/utilities/hooks.spec.ts
src/utilities/hooks.ts

Just realizing we don't need a RouterReplaceError. Simplifying things a bit.

Simplify router push in hooks

---

package-lock.json
package.json

Notice vitepress released an official 1.0 which prompted this

Update some packages to latest versions

---

src/types/resolved.ts
src/types/routerRoute.ts
src/types/routes.ts
src/utilities/createRouterRoutes.ts
src/utilities/getResolvedRouteForUrl.browser.spec.ts
src/utilities/getRouteHooks.spec.ts
src/utilities/paramValidation.spec.ts

renamed Route to RouteProps

---

README.md
docs/core-concepts/defining-routes.md
docs/core-concepts/navigating.md
docs/getting-started.md

went into docs expecting to update after naming changes, but mostly needed to update for push and router-link updates

Docs update

---

src/utilities/createRouter.ts
src/utilities/createRouterHistory.browser.spec.ts
src/utilities/createRouterHistory.ts

ensure from is a clone, break reactivity

Hooks from clone

---

src/components/routerView.vue
src/compositions/useRoute.ts
src/types/resolved.spec-d.ts
src/types/resolved.ts
src/types/route.ts
src/types/utilities.ts
src/utilities/createRouter.spec.ts
src/utilities/createRouter.ts

PR against `writable-params` not `main`

fixed default type for resolved route params

---

docs/.vitepress/config.ts

adds "suggest edits to this page" link at the bottom of our pages

add edit link to theme

---

src/components/routerView.vue

The v-if/v-else prevents a transition from working when going from a route to a rejection or from a rejection to a route. With a single `<component />` tag for both route components and rejections a transition will work the same for both. 
Also adds the rejection to the slot scope

Rework RouterView so that there isn't a v-if/v-else

---

src/guards/routes.ts

isRoute options should be optional

---

src/services/routeRegex.spec.ts
src/services/routeRegex.ts

It was discovered that the route regex service was not escaping regex characters found in the route (outside of params). This meant that something like a period (.) in the path or query was interpreted as ANYTHING, not the literal period as expected.
This PR fixes that bug by instead of using a replace all that only targets param syntax and then passing everything into `new RegExp()`, we instead slit the whole path by the param syntax. For non params we escape regex chars, for params we continue to use catch all. This means a path like 
`/here-i$-an-[example]-path/` gets split into an array of `['/here-i$-an-', '[example]', '-path/']`, which is then joined together as `/here-i\\$-an-.+-path/`

fix bug with non-escaped regex characters in route

---

README.md

Love this project - noticed a typo while reading the docs!

Chore: Fix typo in readme

---

src/types/router.ts

Noticed this doc string wasn't correct so fixing it

Update doc string for history mode

---

README.md
docs/show-me.md

add youtube link to show-me in docs and readme

Add YouTube walkthrough link

---

docs/.vitepress/config.ts
docs/advanced-concepts/prefetching.md
docs/api/components/RouterLink.md
docs/api/types/PrefetchConfigOptions.md
docs/api/types/Route.md

docs update to reflect [the prefetch options PR](https://github.com/kitbagjs/router/pull/255)

updated docs for prefetching

---

src/services/createRouter.ts

Fixes a bug introduced [here](https://github.com/kitbagjs/router/pull/256/files#diff-4fa83539f9cada5e1e1a66209da1753d3e2e5f62353c47bc4b837d33403322e6)

createRouter options might be undefined

---

docs/advanced-concepts/rejections.md
docs/api/interfaces/Register.md

update docs for [this recent PR](https://github.com/kitbagjs/router/pull/256)

updated documentation for recent rejection type change

---

docs/advanced-concepts/route-narrowing.md

this PR fix a missing import and function calling in the docs route narrowing

fix: missing import isRoute in the docs

---

src/components/routerLink.browser.spec.ts
src/compositions/useRoute.browser.spec.ts
src/services/createRouterRoute.spec.ts
src/utilities/components.ts

Fixes some noisy warnings when running tests.

Fix some vue warnings appearing in test runs

---

src/services/createPropStore.ts

Updates the `PropStore` to have a `getPrefetchProps` and `setPrefetchProps` which `useLink` will later utilize.

Add get/set methods for prefetched props

---

package-lock.json
package.json

Vite 6 is out so upgrading things.

Update vite and vite ecosystem packages

---

docs/core-concepts/component-props.md

Adds a new "Context" section to the component prop docs

Add docs for prop context

---

src/components/routerLink.browser.spec.ts
src/types/prefetch.ts

Updates the default prefetch strategy from `eager` to `lazy`

Make the default prefetch strategy lazy

---

docs/advanced-concepts/prefetching.md
src/components/routerLink.browser.spec.ts
src/types/prefetch.ts

Updates the docs to reflect the changes made in https://github.com/kitbagjs/router/pull/342 and https://github.com/kitbagjs/router/pull/349

Update prefetching docs to include `PrefetchStrategy`

---

src/components/routerLink.browser.spec.ts
src/compositions/useLink.ts
src/services/createRouter.spec.ts
src/services/createRouter.ts
src/types/routerReplace.ts

previous lint:fix branch didn't include the changes inside [this bigger PR](https://github.com/kitbagjs/router/pull/371), this fix does

lint:fix again

---

package-lock.json
src/components/routerLink.browser.spec.ts
src/compositions/useEventListener.ts
src/services/createRouter.ts
src/types/utilities.ts

Committing the updates to the package lock that fix linting the project

Fix linting

---

docs/.vitepress/config.ts
docs/advanced-concepts/prefetching.md
docs/core-concepts/component-props.md
docs/core-concepts/routes.md

Docs update for https://github.com/kitbagjs/router/pull/421

Update docs around route `props` being moved to the second argument of `createRoute`

---

src/services/createPropStore.ts
src/services/createRouter.ts
src/services/createRouterHooks.ts
src/services/createVueAppStore.ts
src/services/hooks.spec.ts
src/types/hooks.ts
src/utilities/props.ts
src/utilities/runWithContext.ts

zero impact on users or functionality, just exploring an idea I had to encapsulate some [recent changes](https://github.com/kitbagjs/router/pull/448) into a service.
non-singleton approach to [this PR](https://github.com/kitbagjs/router/pull/475)

moved storage and run with context into "vueAppStore" service

---

docs/api/compositions/useLink.md
docs/api/compositions/useRoute.md
docs/api/compositions/useRouter.md
docs/api/functions/arrayOf.md
docs/api/functions/createExternalRoute.md
docs/api/functions/createParam.md
docs/api/functions/tupleOf.md
docs/api/functions/unionOf.md
docs/api/functions/withDefault.md
docs/api/functions/withParams.md
docs/api/type-guards/isRoute.md
docs/api/types/Param.md
docs/api/types/ResolvedRoute.md
docs/core-concepts/params.md

this PR adds documentation focused around the [recent changes](https://github.com/kitbagjs/router/pull/480) to array param utilities.

Array utility docs update
